FROM alpine:3.20

RUN apk add --no-cache openssl ca-certificates

WORKDIR /opt/cert-init
COPY mailserver/scripts/gen-dev-certs.sh /usr/local/bin/gen-dev-certs.sh
RUN sed -i 's/\r$//' /usr/local/bin/gen-dev-certs.sh && \
    chmod +x /usr/local/bin/gen-dev-certs.sh

ENTRYPOINT ["/bin/sh","-c"]
CMD ["/usr/local/bin/gen-dev-certs.sh"]
