import { FormEvent, ReactNode, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { api, patchJson, postJson, ApiError } from '../../lib/api';
import { formatCents } from '../../lib/money';
import type { DistributorDocument, Product, SaasPlan } from '../../lib/types';

type Any = Record<string, any>;
const msg = (e: unknown) => e instanceof ApiError ? e.message : 'Error inesperado';
const asJson = (v: unknown) => JSON.stringify(v ?? {}, null, 2).slice(0, 500);
function AdminNav(){return <div className="admin-nav"><Link to="/admin">Dashboard</Link><Link to="/admin/distributors">Distribuidores</Link><Link to="/admin/quotes">Presupuestos</Link><Link to="/admin/audit">Auditoría</Link><Link to="/admin/catalog/products">Productos</Link><Link to="/admin/catalog/saas-plans">Planes SaaS</Link></div>}
function Shell({title, children}:{title:string;children:ReactNode}){return <section className="panel"><AdminNav/><h1>{title}</h1>{children}</section>}
function useLoad<T>(url:string){const [data,setData]=useState<T|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true); const load=()=>{setLoading(true);setError('');api<T>(url).then(setData).catch(e=>setError(msg(e))).finally(()=>setLoading(false));}; useEffect(load,[url]); return {data,error,loading,load};}
function State({loading,error,empty}:{loading:boolean;error?:string;empty?:boolean}){if(loading)return <p className="muted">Cargando…</p>; if(error)return <p className="error">{error}</p>; if(empty)return <div className="empty">No hay resultados.</div>; return null;}

export function AdminDashboard(){const {data,error,loading}=useLoad<Any>('/api/admin/dashboard'); const m=data?.metrics??{}; return <Shell title="Dashboard operativo"><State loading={loading} error={error}/>{data&&<><div className="cards compact">{Object.entries(m).map(([k,v])=><article className="card" key={k}><small>{k.replaceAll('_',' ')}</small><h2>{String(k.includes('cents')?formatCents(Number(v)):v)}</h2></article>)}</div><h2>Últimos eventos</h2><Table rows={data.latestAudit}/><h2>Últimos presupuestos</h2><Table rows={data.latestQuotes}/><h2>Últimos distribuidores</h2><Table rows={data.latestDistributors}/></>}</Shell>}
function Table({rows}:{rows:Any[]}){return rows?.length?<div className="table-wrap"><table><tbody>{rows.map((r,i)=><tr key={r.id??i}>{Object.entries(r).map(([k,v])=><td key={k}><small>{k}</small><br/>{typeof v==='object'?asJson(v):String(v??'—')}</td>)}</tr>)}</tbody></table></div>:<div className="empty">Sin datos.</div>}

export function AdminDistributors(){const [q,setQ]=useState(''); const {data,error,loading}=useLoad<Any>(`/api/admin/distributors${q}`); const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault(); const fd=new FormData(e.currentTarget); const p=new URLSearchParams(); ['validation_status','email','company_name'].forEach(k=>{const v=String(fd.get(k)||''); if(v)p.set(k,v)}); setQ(p.size?`?${p}`:'');}; return <Shell title="Distribuidores"><form className="filters" onSubmit={submit}><select name="validation_status"><option value="">Estado</option>{['pending','needs_more_info','approved','rejected','suspended','closed'].map(s=><option key={s}>{s}</option>)}</select><input name="email" placeholder="Email"/><input name="company_name" placeholder="Empresa"/><button>Filtrar</button></form><State loading={loading} error={error} empty={!data?.length}/>{data?.map((d:Any)=><article className="summary" key={d.id}><b>{d.company_name}</b><span>{d.email} · {d.validation_status}</span><Link to={`/admin/distributors/${d.id}`}>Ver detalle</Link></article>)}</Shell>}
export function AdminDistributorDetail(){const {id}=useParams(); const {data,error,loading,load}=useLoad<Any>(`/api/admin/distributors/${id}`); const [notes,setNotes]=useState(''),[busy,setBusy]=useState(''),[ok,setOk]=useState(''); async function change(validation_status:string){setBusy(validation_status);setOk(''); try{await patchJson(`/api/admin/distributors/${id}/status`,{validation_status,review_notes:notes||undefined}); setOk('Estado actualizado'); load();}catch(e){setOk(msg(e));}finally{setBusy('');}} async function doc(docId:string,status:string){const review_notes=status==='rejected'?prompt('Motivo de rechazo obligatorio')||'':''; if(status==='rejected'&&!review_notes)return; setBusy(docId+status); try{await patchJson(`/api/admin/distributor-documents/${docId}/status`,{status,review_notes:review_notes||undefined}); load();}catch(e){alert(msg(e));}finally{setBusy('');}} const d=data?.distributor; return <Shell title="Detalle distribuidor"><State loading={loading} error={error}/>{d&&<><div className="summary"><b>{d.company_name}</b><span>{d.email} · {d.validation_status}</span><span>{d.tax_id}</span></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Notas de revisión"/><div className="actions">{['approved','rejected','needs_more_info','suspended','closed'].map(s=><button disabled={!!busy} key={s} onClick={()=>change(s)}>{s}</button>)}</div>{ok&&<p className={ok.includes('actualizado')?'success':'error'}>{ok}</p>}<h2>Documentos</h2>{data.documents?.map((x:DistributorDocument)=><article className="summary" key={x.id}><b>{x.document_type}</b><span>{x.status} · {x.created_at}</span><div className="actions"><a className="btn" href={`/api/admin/distributor-documents/${x.id}/download`}>Descargar</a><button disabled={!!busy} onClick={()=>doc(x.id,'approved')}>Aprobar</button><button disabled={!!busy} onClick={()=>doc(x.id,'rejected')}>Rechazar</button></div></article>)}</>}</Shell>}

export function AdminQuotes(){const [q,setQ]=useState(''); const {data,error,loading}=useLoad<Any>(`/api/admin/quotes${q}`); const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault(); const fd=new FormData(e.currentTarget), p=new URLSearchParams(); ['status','email','quote_number'].forEach(k=>{const v=String(fd.get(k)||''); if(v)p.set(k,v)}); setQ(p.size?`?${p}`:'');}; return <Shell title="Presupuestos"><form className="filters" onSubmit={submit}><select name="status"><option value="">Estado</option>{['draft','submitted','in_review','sent','accepted','rejected','cancelled'].map(s=><option key={s}>{s}</option>)}</select><input name="email" placeholder="Email"/><input name="quote_number" placeholder="Número"/><button>Filtrar</button></form><State loading={loading} error={error} empty={!data?.quotes?.length}/>{data?.quotes?.map((q:Any)=><article className="summary" key={q.id}><b>{q.quote_number}</b><span>{q.email} · {q.status} · {formatCents(q.total_cents)}</span><Link to={`/admin/quotes/${q.id}`}>Ver detalle</Link></article>)}</Shell>}
export function AdminQuoteDetail(){const {id}=useParams(); const {data,error,loading,load}=useLoad<Any>(`/api/admin/quotes/${id}`); const [notes,setNotes]=useState(''),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState(''); async function change(status:string){setBusy(true); try{await patchJson(`/api/admin/quotes/${id}/status`,{status,internal_notes:notes||undefined}); setFeedback('Estado actualizado'); load();}catch(e){setFeedback(msg(e));}finally{setBusy(false)}} const q=data?.quote; return <Shell title="Detalle presupuesto"><State loading={loading} error={error}/>{q&&<><div className="summary"><b>{q.quote_number}</b><span>{q.email} · {q.status}</span><span>Total: {formatCents(q.total_cents)}</span></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Notas internas"/><div className="actions">{['in_review','sent','accepted','rejected','cancelled'].map(s=><button disabled={busy||q.status==='draft'} key={s} onClick={()=>change(s)}>{s}</button>)}</div>{feedback&&<p className={feedback.includes('actualizado')?'success':'error'}>{feedback}</p>}<h2>Líneas</h2><Table rows={data.items}/><dl className="totals"><div><dt>Subtotal</dt><dd>{formatCents(q.subtotal_cents)}</dd></div><div><dt>Descuento</dt><dd>{formatCents(q.discount_cents)}</dd></div><div><dt>IVA</dt><dd>{formatCents(q.tax_cents)}</dd></div><div className="grand"><dt>Total</dt><dd>{formatCents(q.total_cents)}</dd></div></dl></>}</Shell>}

export function AdminAudit(){const [q,setQ]=useState(''); const {data,error,loading}=useLoad<Any>(`/api/admin/audit${q}`); const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault(); const fd=new FormData(e.currentTarget), p=new URLSearchParams(); ['action','entity_type','actor_user_id','entity_id','date_from','date_to','search','limit'].forEach(k=>{const v=String(fd.get(k)||''); if(v)p.set(k,v)}); setQ(p.size?`?${p}`:'');}; return <Shell title="Auditoría"><form className="filters" onSubmit={submit}>{['action','entity_type','actor_user_id','entity_id','date_from','date_to','search','limit'].map(k=><input key={k} name={k} placeholder={k}/>) }<button>Filtrar</button></form><State loading={loading} error={error} empty={!data?.events?.length}/>{data?.events?.map((e:Any)=><article className="summary" key={e.id}><b>{e.action}</b><span>{e.entity_type} · {e.entity_id ?? '—'} · {new Date(e.created_at).toLocaleString()}</span><span>{e.actor_email ?? e.actor_user_id ?? 'sistema'}</span><pre>{asJson(e.payload)}</pre></article>)}</Shell>}

function CatalogAdmin({kind}:{kind:'products'|'saas-plans'}){const isPlan=kind==='saas-plans'; const {data,error,loading,load}=useLoad<Any>(`/api/admin/${kind}`); const rows=(isPlan?data?.saasPlans:data?.products)??[]; const [editing,setEditing]=useState<Any|null>(null),[feedback,setFeedback]=useState(''); async function save(e:FormEvent<HTMLFormElement>){e.preventDefault(); const fd=new FormData(e.currentTarget); const body:Any={}; ['sku','code','name','description','category'].forEach(k=>{const v=String(fd.get(k)||''); if(v)body[k]=v}); ['price_cents','annual_price_cents','tax_rate','max_tags','max_gateways'].forEach(k=>{const v=String(fd.get(k)||''); if(v)body[k]=Number(v)}); body.is_active=fd.get('is_active')==='on'; if(isPlan)body.is_enterprise=fd.get('is_enterprise')==='on'; if(body.is_enterprise)body.annual_price_cents=null; try{editing?.id?await patchJson(`/api/admin/${kind}/${editing.id}`,body):await postJson(`/api/admin/${kind}`,body); setEditing(null); setFeedback('Guardado'); load();}catch(e){setFeedback(msg(e));}} return <Shell title={isPlan?'Planes SaaS':'Productos'}><button onClick={()=>setEditing({is_active:true,is_enterprise:false})}>Crear</button>{feedback&&<p className={feedback==='Guardado'?'success':'error'}>{feedback}</p>}<State loading={loading} error={error} empty={!rows.length}/>{editing&&<form className="admin-form" onSubmit={save}>{isPlan?<input name="code" defaultValue={editing.code} placeholder="Código"/>:<input name="sku" defaultValue={editing.sku} placeholder="SKU"/>}<input name="name" defaultValue={editing.name} placeholder="Nombre"/><textarea name="description" defaultValue={editing.description} placeholder="Descripción"/>{!isPlan&&<select name="category" defaultValue={editing.category??'hardware'}><option value="hardware">hardware</option><option value="accessory">accessory</option></select>}<input name={isPlan?'annual_price_cents':'price_cents'} type="number" defaultValue={isPlan?editing.annual_price_cents:editing.price_cents} placeholder="Precio céntimos"/><input name="tax_rate" type="number" step="0.01" defaultValue={editing.tax_rate??21} placeholder="IVA"/>{isPlan&&<><input name="max_tags" type="number" defaultValue={editing.max_tags} placeholder="Max tags"/><input name="max_gateways" type="number" defaultValue={editing.max_gateways} placeholder="Max gateways"/><label><input name="is_enterprise" type="checkbox" defaultChecked={editing.is_enterprise}/> Enterprise sin precio automático</label></>}<label><input name="is_active" type="checkbox" defaultChecked={editing.is_active}/> Activo</label><button>Guardar</button></form>}{rows.map((r:Product|SaasPlan)=><article className="summary" key={r.id}><b>{'sku' in r?r.sku:r.code} · {r.name}</b><span>{r.is_active?'activo':'inactivo'} · {'price_cents' in r?formatCents(r.price_cents):r.is_enterprise?'Enterprise':formatCents(r.annual_price_cents)}</span><button onClick={()=>setEditing(r)}>Editar / activar-desactivar</button></article>)}</Shell>}
export const AdminProducts=()=> <CatalogAdmin kind="products"/>;
export const AdminSaasPlans=()=> <CatalogAdmin kind="saas-plans"/>;
