accept_eula = yes
allow_anonymous = off
plugins.vmq_passwd = off
plugins.vmq_acl = off
plugins.vmq_diversity = on
vmq_diversity.auth_postgres.enabled = on
vmq_diversity.auth_postgres.script = /vernemq/share/lua/auth/postgres.lua
vmq_diversity.postgres.password_hash_method = bcrypt
listener.tcp.default = 0.0.0.0:1883
listener.tcp.allowed_protocol_versions = 3,4,5
